# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# Nightly Test Against Open Source Projects Using Xgo
name: Nightly Test

on:
  schedule:
    - cron: "23 0 * * *"
  push:
    branches: [ "trigger-nightly-test" ]
  workflow_dispatch:
    inputs:
      dummy:
        default: nothing

    # 'gin-gonic/gin' ok
    # 'fatedier/frp' cannot pass even with go? need to verify
    #
    # NOTE: use serially job to avoid 'Job Cancelled' which could
    # possible be due to memory exhaust
jobs:

  test-with-xgo:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          path: xgo
          ref: master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      
      - name: Install Xgo Locally
        run: |
          cd xgo
          go install ./cmd/xgo
          xgo revision
      
      - uses: actions/checkout@v4
        with:
          repository: pocketbase/pocketbase
          path:  pocketbase/pocketbase

      - name: Test pocketbase/pocketbase
        continue-on-error: true
        run: cd pocketbase/pocketbase && xgo test -v ./...

      - uses: actions/checkout@v4
        with:
          repository: gohugoio/hugo
          path: gohugoio/hugo

      - name: Test gohugoio/hugo
        continue-on-error: true
        run: cd gohugoio/hugo && xgo test -v ./...

      - uses: actions/checkout@v4
        with:
          repository: kubernetes/kubernetes
          path: kubernetes/kubernetes

      - name: Test kubernetes/kubernetes
        continue-on-error: true
        run: cd kubernetes/kubernetes && xgo test -v ./...
        